### ISSUE TITLE
Unable to read the processed files uploaded at GEO

### ISSUE THREAD

**Issue by jlduan** [alkoenig/Atlas_of_Human_Heart_Failure_Lavine#1]
Hi,

Thanks for generating this useful dataset. I have troubles reading the uploaded R object at  https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE183852.

For example, the GSE183852_DCM_Cells.Robj, 

```
> source("GSE183852_DCM_Cells.Robj")
Error in source("GSE183852_DCM_Cells.Robj") : 
  GSE183852_DCM_Cells.Robj:4:1: unexpected input
3: 
4: 
   ^
```

These are the md5sum:
```
$ md5sum GSE183852_DCM_Cells.Robj.gz
51d546333d2943269806b6ee32f0e369  GSE183852_DCM_Cells.Robj.gz

$ md5sum GSE183852_DCM_Cells.Robj
6b6118eb9612e5b79e380d9720c5e9e5  GSE183852_DCM_Cells.Robj
```

I am wondering if these files are corrupted. Thanks for your help!

Best,

**Comment by alkoenig** [comment]
Hello!

I just checked and the checksum appears to match for the uncompressed file. These files are the processed Seurat objects saved as .robj files. You should be able to load them running load("GSE183852_DCM_Cells.Robj") as long as the Seurat package is loaded. Please feel free to let me know if you still have issues loading them.
