### ISSUE TITLE
Pie chart

### ISSUE THREAD

**Issue by levinhein** [alkoenig/Atlas_of_Human_Heart_Failure_Lavine#2]
Hello. May I kindly ask if you can share your code how you generated your pie charts? Thanks a lot!

**Comment by alkoenig** [comment]
Hi! Pie charts were actually made using Graphpad Prism with the cell numbers per cluster exported from R: >write.table(table(Object$Names), "Number_cells_by_type.tsv", sep="\t", quote=F)

**Comment by levinhein** [comment]
Thank you very much!
