### ISSUE TITLE
snRNA nuclei object is missing metadata

### ISSUE THREAD

**Issue by KalinNonchev** [alkoenig/Atlas_of_Human_Heart_Failure_Lavine#3]
Hello,

thank you for sharing your dataset - https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE183852
I noticed that the metadata is missing for the snRNA nuclei dataset, so the user has to add it manually using your [script](https://github.com/alkoenig/Atlas_of_Human_Heart_Failure_Lavine/blob/main/DCM_Nuclei_Seurat.R).
It would be nice if you can update the nuclei object and include the metadata.

Best,

**Comment by alkoenig** [comment]
Hi Kalin,

Thank you for bringing this to my attention. The age group and sex metadata for the snRNA object should be able to be imported from the integrated object using the AddMetaData function from the Seurat package. Much of the analysis on these variables was completed outside of the Seurat object and therefore did not end up included in the final object.
